languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hyde-hyde"

title = "SpeedCode"
baseURL = "https://fuhrmannb.me/"
enableRobotsTXT = true

[params]
    author = "Benjamin FÜHRMANN"
    authorimage = "/img/fuhrmannb.jpg"
    copyright = "fuhrmannb"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

    showBuiltWith = true
    showpagemeta = true

    UtterancesRepo = "fuhrmannb/fuhrmannb-utterances"
    UtterancesIssueTerm = "pathname"
    UtterancesTheme = "github-light"

[languages]
    [languages.en]
        languageName = "English"
        [languages.en.params]
            description = "A place where we take the time to code fast"
        [[languages.en.menu.main]]
            name = "About"
            identifier = "about"
            weight = 100
            url = "/about/"
        [[languages.en.menu.main]]
            name = "Blog"
            weight = 200
            identifier = "blog"
            url = "/posts/"
        [[languages.en.menu.main]]
            name = "Resume"
            identifier = "resume"
            weight = 300
            url = "/resume/"

    [languages.fr]
        languageName = "Français"
        [languages.fr.params]
            description = "Un endroit où on prend le temps de coder vite"
        [[languages.fr.menu.main]]
            name = "À propos"
            identifier = "about"
            weight = 100
            url = "/about/"
        [[languages.fr.menu.main]]
            name = "Blog"
            weight = 200
            identifier = "blog"
            url = "/posts/"
        [[languages.fr.menu.main]]
            name = "CV"
            identifier = "resume"
            weight = 300
            url = "/resume/"


[params.social]
    github = "fuhrmannb"
    linkedin = "benjamin-führmann-54174862"
    twitter = "fuhrmann_b"
    stackoverflow = "3601426"
    email = "benjamin.fuhrmann@gmail.com"