languageCode = "en-us"
theme = "hyde-hyde"
DefaultContentLanguage = "en"
baseURL = "https://fuhrmannb.me"

[params]
    author = "Benjamin FÜHRMANN"
    authorimage = "/img/fuhrmannb.jpg"

    copyright = "fuhrmannb"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true
    UtterancesRepo = "fuhrmannb/fuhrmannb-utterances"
    UtterancesIssueTerm = "pathname"
    UtterancesTheme = "github-light"

[languages]
    [languages.en]
        languageName = "English"
        title = "What a code!"
        [languages.en.params]
            description = "Jumble and other fun stuff I want to share"
        [[languages.en.menu.main]]
            name = "About"
            identifier = "about"
            weight = 100
            url = "/about/"
        [[languages.en.menu.main]]
            name = "Blog"
            weight = 200
            identifier = "blog"
            url = "/blog/"
        [[languages.en.menu.main]]
            name = "Resume"
            identifier = "resume"
            weight = 300
            url = "/resume/"

    [languages.fr]
        languageName = "Français"
        title = "Quel code!"
        [languages.fr.params]
            description = "Bric-à-brac et autres trucs cools que j'ai envie de partager"
        [[languages.fr.menu.main]]
            name = "À propos"
            identifier = "about"
            weight = 100
            url = "/about/"
        [[languages.fr.menu.main]]
            name = "Blog"
            weight = 200
            identifier = "blog"
            url = "/blog/"
        [[languages.fr.menu.main]]
            name = "CV"
            identifier = "resume"
            weight = 300
            url = "/resume/"


[params.social]
    github = "fuhrmannb"
    linkedin = "benjamin-führmann-54174862"
    twitter = "fuhrmann_b"
    stackoverflow = "3601426"
    email = "benjamin.fuhrmann@gmail.com"